server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: url-service-shorten
              uri: ${URL_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/urls/**
                - Method=POST
              filters:
                - name: RequestRateLimiter
                  args:
                    rate-limiter: "#{@writeRateLimiter}"
                    key-resolver: "#{@ipKeyResolver}"

            - id: url-service-redirect
              uri: ${URL_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/{shortCode:[a-zA-Z0-9]+}
              filters:
                - PrefixPath=/api/v1/urls
                - name: RequestRateLimiter
                  args:
                    rate-limiter: "#{@readRateLimiter}"
                    key-resolver: "#{@ipKeyResolver}"

            - id: analytics-service-api
              uri: ${ANALYTICS_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/analytics/**

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}