spring:
  application:
    name: url-shortener

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

app:
  cleanup:
    cron: "0 0 2 * * *"
    grace-period-days: 30
  url:
    cache-ttl: 1d
    negative-cache-ttl: 30s
    expired-cache-ttl: 30m
    default-ttl-days: 30
    max-save-retries: 5