CREATE TABLE urls
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_url TEXT                                    NOT NULL,
    short_code   VARCHAR(10)                             NOT NULL,
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pk_urls PRIMARY KEY (id)
);

ALTER TABLE urls
    ADD CONSTRAINT uc_urls_shortcode UNIQUE (short_code);