CREATE TABLE url_clicks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    short_code VARCHAR(10)                             NOT NULL,
    clicked_at TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    user_agent VARCHAR(512),
    ip_address VARCHAR(45),
    referer    TEXT,
    CONSTRAINT pk_url_clicks PRIMARY KEY (id)
);

CREATE INDEX idx_url_clicks_shortcode ON url_clicks(short_code);
CREATE INDEX idx_url_clicks_clickedat ON url_clicks(clicked_at);